/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import VisualesGrafo.GraphStreamGrafo;
import javax.swing.JOptionPane;
import proyecto.pkg1.irina.Grafo;

public class InterfazMAIN extends javax.swing.JFrame {
    private Grafo grafo;
    private Archivos.LectorArchivo Lector;

    /**
     * Creates new form InterfazMAIN
     */
    public InterfazMAIN() {
        initComponents();
        grafo = new Grafo();
        Lector = new Archivos.LectorArchivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BotonCargarArchivos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        InputAgregarUser = new javax.swing.JTextField();
        BotonAgregarUSER = new javax.swing.JButton();
        InputAgregarConexion = new javax.swing.JTextField();
        BotonAgregarCONEXION = new javax.swing.JButton();
        BotonEliminarUSER = new javax.swing.JButton();
        InputElimUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BotonActualizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BotonVisualizarGrafo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Análisis de redes sociales");

        BotonCargarArchivos.setBackground(new java.awt.Color(153, 204, 255));
        BotonCargarArchivos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BotonCargarArchivos.setText("Cargar Archivo");
        BotonCargarArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCargarArchivosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Si hay cambios en los usuarios haga click en actualizar");

        InputAgregarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputAgregarUserActionPerformed(evt);
            }
        });

        BotonAgregarUSER.setBackground(new java.awt.Color(153, 204, 255));
        BotonAgregarUSER.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BotonAgregarUSER.setText("Agregar usuario");
        BotonAgregarUSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarUSERActionPerformed(evt);
            }
        });

        BotonAgregarCONEXION.setBackground(new java.awt.Color(153, 204, 255));
        BotonAgregarCONEXION.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BotonAgregarCONEXION.setText("Agregar conexión");
        BotonAgregarCONEXION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarCONEXIONActionPerformed(evt);
            }
        });

        BotonEliminarUSER.setBackground(new java.awt.Color(153, 204, 255));
        BotonEliminarUSER.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BotonEliminarUSER.setText("Eliminar usuario");
        BotonEliminarUSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarUSERActionPerformed(evt);
            }
        });

        InputElimUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputElimUserActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Usuarios: agreguelos de la siguiente manera, @nombre");

        BotonActualizar.setBackground(new java.awt.Color(153, 204, 255));
        BotonActualizar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BotonActualizar.setText("Actualizar");
        BotonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Cargue el documento txt");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Visualización del Grafo");

        BotonVisualizarGrafo.setBackground(new java.awt.Color(153, 204, 255));
        BotonVisualizarGrafo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BotonVisualizarGrafo.setText("Visualizar");
        BotonVisualizarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVisualizarGrafoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(BotonActualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel5)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(InputElimUser, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InputAgregarConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InputAgregarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonEliminarUSER)
                    .addComponent(BotonAgregarCONEXION)
                    .addComponent(BotonAgregarUSER))
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(BotonCargarArchivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(BotonVisualizarGrafo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonAgregarUSER)
                            .addComponent(InputAgregarUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonAgregarCONEXION)
                            .addComponent(InputAgregarConexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonCargarArchivos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputElimUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonEliminarUSER))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonActualizar)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addComponent(BotonVisualizarGrafo)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarUSERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarUSERActionPerformed

        if (grafo == null || grafo.getCantidad() == 0) {
            JOptionPane.showMessageDialog(this, "Aun no hay un archivo cargado", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            String nombre = InputAgregarUser.getText().trim();
            if (!nombre.isEmpty()) {
                boolean agregando = grafo.addUsers(nombre);
                if (agregando) {
                    JOptionPane.showMessageDialog(this, "El usuario que usted agrego fue: " + nombre);
                    InputAgregarUser.setText("");
                }else{
                    JOptionPane.showMessageDialog(this, "El usuario que usted ingreso ya existe en la lista, ingrese uno diferente");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ingresa un nombre de usuario valido por favor :)");
        }
    }//GEN-LAST:event_BotonAgregarUSERActionPerformed

    private void BotonAgregarCONEXIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarCONEXIONActionPerformed
        // TODO add your handling code here:
        if (grafo == null || grafo.getCantidad() == 0) {
            JOptionPane.showMessageDialog(this, "Aun no hay un archivo cargado", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            String texto = InputAgregarConexion.getText().trim();
            if (texto.contains(",")) {
                String[] partesTexto = texto.split(",");
                String enlace1 = partesTexto[0].trim();
                String enlace2 = partesTexto[1].trim();
                grafo.addConexion(enlace1, enlace2);
                JOptionPane.showMessageDialog(this, "Se agrego la conexio: " + enlace1 + "," + enlace2);
                InputAgregarConexion.setText("");                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Formato invalido, ingreselo como: usuario1,usuario2");
        }
    }//GEN-LAST:event_BotonAgregarCONEXIONActionPerformed

    private void BotonEliminarUSERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarUSERActionPerformed
        try {
            String nombre = InputElimUser.getText().trim();
            if (!nombre.isEmpty()) {
                grafo.deleteUser(nombre);
                JOptionPane.showMessageDialog(this, "Elimino a: " + nombre + " de la lista de usarios");
                InputElimUser.setText("");                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre válido");
        }
    }//GEN-LAST:event_BotonEliminarUSERActionPerformed

    private void InputAgregarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputAgregarUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputAgregarUserActionPerformed

    private void InputElimUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputElimUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputElimUserActionPerformed

    private void BotonCargarArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCargarArchivosActionPerformed
        try {
            Grafo newGrafo = Lector.CargarGrafodesdeArchivo();
            if (newGrafo != null) {
                this.grafo = newGrafo;
                grafo.printGrafo();
                JOptionPane.showMessageDialog(this, "Su archivo fue cargado y listo para su uso");   
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se pudo cargar el archivo, asegurese de que eligio el correcto y que este sea un archivo txt");
        }
    }//GEN-LAST:event_BotonCargarArchivosActionPerformed

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
        Lector.actualizarRepo(grafo);
    }//GEN-LAST:event_BotonActualizarActionPerformed

    private void BotonVisualizarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVisualizarGrafoActionPerformed
        if (grafo == null || grafo.getCantidad() == 0) {
            JOptionPane.showMessageDialog(this, "Aun no hay un archivo cargado", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (grafo != null && grafo.getCantidad() > 0) {
            grafo.Kosaraju();
            GraphStreamGrafo.Show(grafo);
        } else {
            JOptionPane.showMessageDialog(this, "No hay grafo cargado o está vacío.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_BotonVisualizarGrafoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazMAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazMAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazMAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazMAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazMAIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JButton BotonAgregarCONEXION;
    private javax.swing.JButton BotonAgregarUSER;
    private javax.swing.JButton BotonCargarArchivos;
    private javax.swing.JButton BotonEliminarUSER;
    private javax.swing.JButton BotonVisualizarGrafo;
    private javax.swing.JTextField InputAgregarConexion;
    private javax.swing.JTextField InputAgregarUser;
    private javax.swing.JTextField InputElimUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    // End of variables declaration//GEN-END:variables
}
